# 项目相关配置
ruoyi:
  #文件上传路径
  profile: /lanh/uploadPath


life:
  wx:
    notify-url:  http://49.235.38.60/wx/order/pay-notify

spring:
    profiles: prod
    datasource:
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://212.64.90.78:3306/life_classroom?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: life_classroom
                password: C6a8HKp6shNXiHjJ

